{% set version = "0.7" %}

package:
    name: nitime
    version: {{ version }}

source:
    fn: nitime-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/n/nitime/nitime-{{ version }}.tar.gz
    md5: 4055597dac1cede57ff9a16d609c9fe0

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - numpy x.x
        - cython
        - setuptools
    run:
        - setuptools
        - python
        - numpy x.x
        - scipy
        - matplotlib
        - networkx
        - nibabel

test:
    imports:
        - nitime
        - nitime.algorithms
        - nitime.algorithms.tests
        - nitime.analysis
        - nitime.analysis.tests
        - nitime.fmri
        - nitime.fmri.tests
        - nitime.tests

about:
    home: http://nipy.org/nitime
    license: BSD-3-Clause
    summary: Timeseries analysis for neuroscience data

extra:
    recipe-maintainers:
        - arokem
        - ocefpaf
