travis:
  secure:
    BINSTAR_TOKEN: jM4575+FMUYYTGPiYg1ApLWVb7k6As6cpIIv6/NzYZosqmYZPpRiX05EFFJhUAvRSMPZYVhepdEDaVf7bksAWkNpxdBxWIPHR+eSaW+T4HrLkVt9QS1+otTtEAlXuuj0gSdaGlNxb717WoXL8uQbYZHJ7gyY4MnzhKTah30yi2fZxQSWqSnS+vuLLRS7k3C5mUAbGLmWONXTJ15Mvz2sVIDNTMe6EDgv2m33cpEHU/HooYPPKr7DstVBgj0GOsGGeYiI3zQgNsKrvCUxZ2Mb3E66WMUTeO5/mr36S42EOJmxYgo/LGDIa1h7ruL8CHaiHEAvj7M9ANJcQYalaWcc5GfXwDiGcK6qxiDg3yATvRD19NaZ+l5KkW2/WIABXPP80OMQh08T9jtrxYH7r5NsrhuRMCWWxrw9CD5uMZlsJs8dikta3juSfblrXVfmjbvJTdKCCVjfrAvx6KSkEa/A55cTgPLpwAnr0ug7ZRGmCzOkh1ZB07TaP55M+I+D/B7unwTw3PImWZwJzwM0WBSl0KDpDbF859nCFLcw5QVbmTFweXT6SDZL2vkrVF2U1HxsYV1KKVeFj5CpjBG6jsoGsERTsQzwv7xVJl/TurglilshbbNZ75WQwhULCn6UuMjPv0KtX5I3tsENG/FCi7yB1OBDBCeiUqglb57Qosk2YUw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
